### ISSUE TITLE
DataBinder: FormatException column details

### ISSUE THREAD

**Issue by vgebrev** [MarkPflug/Sylvan#108]
Hi,

Thank you for a great library.

I am using the DataBinder to map a csv file to a parse result POCO.

Most fields are strings, but some DateTimes and others are decimals.

If a FormatException is thrown during the binding, there doesn't seem to be a way of determining which specific column the offending data is in. Is there way to determine this?

Thank you.

**Comment by vgebrev** [comment]
fileStream.Seek(0, SeekOrigin.Begin);
            var csvDataReaderOptions = new CsvDataReaderOptions()
            {
                Schema = new ImportCsvSchema().Schema
            };
            using var streamReader = new StreamReader(fileStream, Encoding.UTF8, leaveOpen: true);
            using var csvReader = CsvDataReader.Create(streamReader, csvDataReaderOptions) ;
            var binder = DataBinder.Create<TParseResult>(csvReader, new DataBinderOptions() { BindingMode = DataBindingMode.AllColumns });
            while (csvReader.Read())
            {
                try
                {
                    binder.Bind(csvReader, parseResult);
                }
                catch (Exception exception)
                {
                    // TODO: Figure out which column was being parsed/bound
                }
            }

columns are mostly strings, but a few DateTimes and Decimals as follows:
`new Column.Builder( nameof(CsvParseResult.Date), typeof(DateTime), allowNull: true).Build(),`
`new Column.Builder( nameof(CsvParseResult.Amount), typeof(decimal), allowNull: true).Build(),`

**Comment by vgebrev** [comment]
Holy smokes, that was quick! Thank you kindly, that was exactly what I needed.

**Comment by MarkPflug** [comment]
If you've found these libraries useful, give it a star, helps other people find it.
