### ISSUE TITLE
CsvRecordTooLargeException if there is no blank line in the end

### ISSUE THREAD

**Issue by rmotyka** [MarkPflug/Sylvan#109]
The exception occurs only if there is no header row and there is only one row with data in the CSV file.

**Comment by MarkPflug** [comment]
Can you provide an example file and code taht exhibits the problem? I have tests that cover this case, and I can't reproduce.

**Comment by rmotyka** [comment]
I create the reader:
`using var csv = CsvDataReader.Create("file.csv", options);`
with options:

`var options = new CsvDataReaderOptions
            {
                Schema = new CsvSchema(tableSchema),
                Delimiter = '|',
                HasHeaders = false,
                Culture = CultureInfo.InvariantCulture,
                CsvStyle = CsvStyle.Escaped,
            };`

the file is something like that:
`en-US|11/9/2019|0|IL|0|11|12|13|14`

if there is no additional empty line, or there is no header, or there are no more lines the error appears. I've checked that with the source code. There is "Result.Incoplete" returned somewhere but I've found the code to be very performance-optimized (well less readable as well). I work on Windows.

**Comment by MarkPflug** [comment]
>the file is something like that:
en-US|11/9/2019|0|IL|0|11|12|13|14

I still cannot reproduce the error using these details.
You are using the latest version of the library? 1.1.11?
The file is one single line? How big is the file? Can you add the file to this issue?

**Comment by MarkPflug** [comment]
Thanks, I was able to repro with the sample you sent. Fixed the issue in 1.1.12 which I just pushed to nuget. If you've found these projects helpful, please give the repo a star to help other discover it.
