### ISSUE TITLE
Fast XML parser

### ISSUE THREAD

**Issue by adamradocz** [MarkPflug/Sylvan#117]
Hi,

Do you have any solutions for parsing XML fast? Like, really fast. 😄 

Thank you!

**Comment by MarkPflug** [comment]
The in-built System.Xml.XmlReader is quite fast. However, it requires using it properly to achieve the best performance, which can be hard. I think very few people use it directly, and instead use XmlDocument.Load to load the entire document at once.

I used `XmlReader` to implement .xlsx support in my Excel data library, which is the fastest in class: [benchmarks](https://github.com/MarkPflug/Benchmarks/blob/main/docs/ExcelBenchmarks.md). Nearly twice as fast as the second fastest, and orders of magnitude less memory allocation. One key trick is to use low level APIs like `ReadValueChunk` which can be used to avoid allocations. [Example](https://github.com/MarkPflug/Sylvan.Data.Excel/blob/e4a7287cc95c69d0b92748b7a7b748266a85ae2f/source/Sylvan.Data.Excel/Xlsx/XlsxWorkbookReader.cs#L532-L533)

**Comment by adamradocz** [comment]
Thanks.
