### ISSUE TITLE
does not contain a definition for "AsDataReader" or an accessible extension method "AsDataReader"

### ISSUE THREAD

**Issue by juanpablogd** [MarkPflug/Sylvan#118]
using Sylvan.Data;
using Sylvan.Data.Csv;

Error CS1061 "List<string>" does not contain a definition for "AsDataReader" or an accessible extension method "AsDataReader" that accepts a first argument of type "List<string>" (are you missing a using directive or an assembly reference?

**Comment by MarkPflug** [comment]
I don't know what "`List`" is. You would need to be using the generic `System.Collections.Generic.List<T>`, or some other type that implements `IEnumerable<T>`.

https://github.com/MarkPflug/Sylvan/blob/db37f3f4708c0e30fb060c609667638e86af3a91/source/Sylvan.Data/DataExtensions.cs#L48
