### ISSUE TITLE
GetDate (.net 6) doesn't respect DateFormat options

### ISSUE THREAD

**Issue by dylanwilson80** [MarkPflug/Sylvan#139]
Let me first just say I've only been using this library for a little while but I love it. It's great to see a really well thought out CSV library.

Anyway, I have a CSV file with dates in Australian format (`dd/MM/yyyy`).  I tried parsing the file with:

```
var options = new CsvDataReaderOptions { DateFormat = "dd/MM/yyyy" };
```

Followed by:

```
csv.GetDate(2)
```

But it throws the following exception:

> String '30/06/2022' was not recognized as a valid DateOnly.

To workaround the issue I created a simple extension method:

```
    public static DateOnly GetDateOnly(this CsvDataReader reader, int ordinal)
    {
        var dateTime = reader.GetDateTime(ordinal);
        return DateOnly.FromDateTime(dateTime);
    }
```

This will do just fine for now but I just thought I'd report it in case you'd like to know.

**Comment by dylanwilson80** [comment]
I used to run an open source project so I completely understand the challenges involved trying to balance breaking the API with adding new features.

I did have one random thought looking at your existing API... 

Currently you've got an option called `DateFormat` which controls the format of the `GetDateTime` method and returns a `DateTime`. In hindsight maybe the option should have been called `DateTimeFormat`.

In the same vein, it might make sense to have an option called `DateOnlyFormat` which controls the `GetDate` method that returns a `DateOnly`. But again, I'm just spitballing a few ideas. You obviously know your library better than I do so you're welcome to take it or leave it.

To provide a little more context around the app I'm currently building...

The user of my app will be exporting CSV files from another app and importing them into my app. But the exact format of the input CSV file isn't known at compile time so I'm going to allow the user to specify the schema during the import process. In other words, I'm going to let them choose the columns they want to import and specify the date formats on the fly.

So I really appreciate that your library provides a way to specify the schema. This should work great for what I'm trying to achieve. It will also make sense to use the users culture to have sensible defaults for the date formats.

Thanks again.

**Comment by MarkPflug** [comment]
I just pushed v1.2.0-b0001 (prerelease) to nuget. Along with other changes, this adds the `DateOnlyFormat`. I'll be pushing a final release soon, so if you want it give it a try you have an opportunity to give me some feedback.

**Comment by dylanwilson80** [comment]
Sorry for taking a while to get back to you about this.

I have switch my project over to use the  v1.2.0-b0001 (prerelease) package and everything is workng:

 - It correctly reported the `DateFormat` option as deprecated and told me what to do
 - Despite the deprecated warning my code still worked (no breaking changes)
 - I refactored the code to use `DateTimeFormat`, `DateOnlyFormat` and `GetDate` where appropriate and everything still works

Thanks for the great work
