### ISSUE TITLE
Doesn't distinguish between empty string and null

### ISSUE THREAD

**Issue by itamarep** [MarkPflug/Sylvan#154]
When reading a file written by CsvDataWriter.
If Schema = CsvSchema.Nullable all empty strings are null
if Schema is default, all empty strings are empty strings
There needs to be a way to diffrentiate between the two

The fix I did locally was in CsvWriter.cs => WriteValueOptimistic if the length of the value is 0, return NeedsQuoting
This will create a difference between empty string and null when reading with Schema = CsvSchema.Nullable

**Comment by MarkPflug** [comment]
CsvSchema.Nullable applies the nullability behavior to all columns. It is possible to provide a different ICsvSchemaProvider that will provide different nullability for different columns. This can allow an empty field to be read as null in one column, and as an empty string in another. Would that satisfy your needs? Or do you need to have empty string and null within the same column?

**Comment by itamarep** [comment]
The issue was not reading the file, but distinguishing between null and
empty string in a file that was written by CsvWriter, both are written the
same way

**Comment by MarkPflug** [comment]
I just published Sylvan.Data.Csv 1.2.1 to nuget. You can now set `CsvDataWriterOptions.QuoteEmptyStrings = true` to cause empty strings to be written as quoted empty fields.
