### ISSUE TITLE
Non-descript exception thrown for Sylvan.Data.Csv

### ISSUE THREAD

**Issue by iamadamreed** [MarkPflug/Sylvan#201]
A specific line in a file continues to throw this exception, I cannot gleam any more data or reason as to why it's throwing this exception. 

I unfortunately cannot share the CSV line as it contains confidential information, but I was hoping someone might have an idea as to how I can debug further? 

Exception of type 'Sylvan.Data.Csv.CsvFormatException' was thrown

   at Sylvan.Data.Csv.CsvDataReader.ReadField(Int32 fieldIdx)
   at Sylvan.Data.Csv.CsvDataReader.<NextRecordAsync>d__6.MoveNext()
   at Sylvan.Data.Csv.CsvDataReader.<ReadAsync>d__8.MoveNext()
   at SomeFileReader.<GetAllRecords>d__3.MoveNext() in 
   
   
![image](https://github.com/MarkPflug/Sylvan/assets/16042069/a46b1b4e-478c-4774-903c-5ce3aa1c21be)

**Comment by adamreed90** [comment]
I was able to locate the issue, in the 8th ordinal of my file, it was a quoted text field with a quote inside it, like so: 

```
0,1,2,3,4,5,6,7,"this is the "example" of the quoted text field"
```

**Comment by adamreed90** [comment]
> Those quotes would need to be escaped (doubled up) to make it a valid CSV file.

Indeed, do you have any suggestions as to how I could detect this specific issue in files, so I may fail specifically and gracefully? 
The CsvFormatException didn't provide any specific failure.

Thanks for an awesome library!

**Comment by loop-evgeny** [comment]
I've run into this useless exception as well. PR with useful exception messages: #269
