### ISSUE TITLE
Fields ending in escaped character return the wrong character

### ISSUE THREAD

**Issue by ejdownescx** [MarkPflug/Sylvan#220]
Found this while parsing a CSV file with backslash as an escape character, and in this case no quoted strings. If an escaped comma is the last character in a field, the result will have the wrong final character. It will return the escape character instead of the character after it.

```csharp
	[Fact]
	public void FinalCharInCellIsEscaped()
	{
		using var reader = new StringReader(@"a\, \,,b");
		using var csvReader = CsvDataReader.Create(reader, new CsvDataReaderOptions
		{
			CsvStyle = CsvStyle.Escaped,
			HasHeaders = false,
			Escape = '\\',
		});

		csvReader.Read();
		var value0 = csvReader.GetString(0);
		var value1 = csvReader.GetString(1);
		Assert.Equal("a, ,", value0); // This will fail; will be "a, \" instead of "a, ,"
		Assert.Equal("b", value1);
	}
```

Seems like the cause is an off by 1 issue in CsvDataReader.cs in the PrepareField method:

```csharp
				if (c == escape && i + 1 < len) // off by 1
```

```csharp
				if (c == escape && i < len) // fixes issue; all tests pass
```

**Comment by MarkPflug** [comment]
Thanks for reporting the bug, and providing the fix.
This is fixed with 1.3.5, which I just published to nuget. (might take a while to show up in the index)
