### ISSUE TITLE
Minor unescape issue?

### ISSUE THREAD

**Issue by nietras** [MarkPflug/Sylvan#223]
Hi @MarkPflug, during examination of unescaping I've discovered Sylvan appears to output something weird for "invalid" col text, so treat this issue as you wan't just wanted to let you know.

Given input `"a"""a"` (entire content of file/source, no new lines) then Sylvan will output `a"a<NULL>`, where `<NULL>` is in fact 0. I presume that might be an issue. I understand this is a degenerate and invalid case but it can happen at end of a file. Tested with 1.3.5.

**Comment by MarkPflug** [comment]
Definitely looks like a bug, thanks for bringing it to my attention.

**Comment by MarkPflug** [comment]
Fixed in the next release, 1.3.6.
