### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by nk-cmd** [MarkPflug/Sylvan#234]
Hi Mark, 

I have an Encoding issue and maybe I have missed someting.
I changed the Encoding to default or Encoding.UTF8, but the value is always the same

```
if (stream.CanSeek) { stream.Seek(0, SeekOrigin.Begin); }

TextReader tx = new StreamReader(stream, **true**);
var opt = new CsvDataReaderOptions();

var pool = new StringPool(20);
var separator = HandleSeparator(separatorEnum);
if (separator != null)
{
    opt.Delimiter = separator;
}
opt.OwnsReader = false;
opt.StringFactory = pool.GetString;
var dataReader= await CsvDataReader.CreateAsync(tx, opt);
....
var val = dataReader.GetValue(columName)
```

![image](https://github.com/MarkPflug/Sylvan/assets/62747555/e3f5e00b-9465-4a91-aced-8d7439d3dd5b)

![image](https://github.com/MarkPflug/Sylvan/assets/62747555/5a867474-65a5-40cf-875d-c739acfb7502)

Can you check this?

Thanks,
nk-cmd

**Comment by MarkPflug** [comment]
You would have to provide me the file, otherwise I'd only be guessing.
This definitely looks like an encoding issue though.

**Comment by MarkPflug** [comment]
That file appears to be using [ISO-8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) encoding, or possibly Windows-1252. The `detectOrderFromByteOrderMarks` flag, will use the Unicode BOM to identify which Unicode encoding is being used, and if there is no BOM (as in this file) it will default to Utf-8. So, the StreamReader ends up using the wrong encoding for this file.

You can fix this, by specifying the `Latin1` encoding explicitly:
using var r = new StreamReader(s, Encoding.Latin1);

```C#
            // make sure the console is writing an encoding
            // that can display all characters.
            Console.OutputEncoding = Encoding.UTF8;

            using var r = new StreamReader("error_ft.csv", Encoding.Latin1);
            using var csv = CsvDataReader.Create(r);
            while (csv.Read())
            {
                for (int i = 0; i < csv.RowFieldCount; i++) {
                    Console.WriteLine(csv.GetString(i));
                }
                Console.WriteLine("------");
            }
```

This will write the correct values from the file.
