### ISSUE TITLE
DataTable Columns and Rows 

### ISSUE THREAD

**Issue by nk-cmd** [MarkPflug/Sylvan#237]
Hi Mark,

I have a strange behavior with your csv and excel package.

If I check the columns and rows from the dataTable, There are the properties of DbColumn and not the columns of the source file

```
 if (stream.CanSeek) { stream.Seek(0, SeekOrigin.Begin); }

 TextReader tx = new StreamReader(stream, Encoding.Latin1);
 var opt = new CsvDataReaderOptions();

 var pool = new StringPool(20);
 opt.OwnsReader = false;
 opt.StringFactory = pool.GetString;
 var file = await CsvDataReader.CreateAsync(tx, opt);
 var dataTable = file.GetSchemaTable();

```

![image](https://github.com/MarkPflug/Sylvan/assets/62747555/0134fa12-8e5b-4732-9bcf-5b6493f8080a)

**Comment by MarkPflug** [comment]
That is correct, and expected. `GetSchemaTable` returns a DataTable that contains the schema information about the CSV file. The way that GetSchemaTable presents the data is a bit hard to work with though, which is why I'd recommend you use GetColumnSchema if that's what you need.

I suspect though, that you're trying to load the CSV *data* (not schema) into a DataTable. If that's the case, then it can be done quite easily:

```C#
        var data =
            """
            a,b,c
            1,2,3
            4,5,6
            """;

        var csv = CsvDataReader.Create(new StringReader(data));

        var dt = new DataTable();
        dt.Load(csv);
```

**Comment by MarkPflug** [comment]
You might look at the Sylvan.Data package, which contains the `Sylvan.Data.SchemaAnalyzer` type, which can be used to determine the data types of columns in "untyped" data sets. It works with both the Sylvan CSV and Excel readers.

```C#
var data =
    """
    a,b,c
    1,2,3
    4,5,6
    """;

Sylvan.Data.Schema schema;
using (var csv = CsvDataReader.Create(new StringReader(data)))
{
    // analyzing the schema "consumes" the data reader
    // it looks at the string values and determines if they
    // represent a numeric (int, double, decimal), datetime, etc.
    schema = AnalyzeSchema(csv);
}

using (var csv = CsvDataReader.Create(new StringReader(data), new CsvDataReaderOptions {  Schema = new CsvSchema(schema) }))
{
    var dt = new DataTable();
    dt.Load(csv);
    // data table is now loaded with strongly-typed (instead of stringly-typed) data.
}

static Sylvan.Data.Schema AnalyzeSchema(DbDataReader reader)
{
    var sa = new Sylvan.Data.SchemaAnalyzer();
    var result = sa.Analyze(reader);
    var schema = result.GetSchema();
    return schema;
}
```
