### ISSUE TITLE
Reading many csv files, checking the length of fields and merging them all into one file

### ISSUE THREAD

**Issue by BabakRabie** [MarkPflug/Sylvan#238]
What is the fastest way to read thousands of csv files in a loop, check each field for the size (i.e. less than 25) , add a row number to the columns and at the end merge them into one big csv file? I know how to do read, check and add the row number  but not sure  what would be the fastest way to merge them into a big file.

**Comment by BabakRabie** [comment]
// add line number and filename 
                    // This code generates one file per each input file. But I need the output to be merged to one output file
                    foreach (string file in files)
                    {
                        try
                        {

                            fileName = file.Split('\\')[file.Split('\\').Length - 1];
                            fileNameNoExt = fileName.Split('.')[0];
                            dateInFileName = fileNameNoExt.Split('_')[4];
                            dr = CsvDataReader.Create(file, readerOptions);

                            dr2 = dr.WithColumns(
                                new CustomDataColumn<string>("FilenameNoExt", _ => fileNameNoExt),
                                new CustomDataColumn<string>("DateInFilename", _ => dateInFileName),
                                new CustomDataColumn<int>("Row", _ => dr.RowNumber)
                                );
                        }
                        catch
                        {
                            Console.WriteLine($"file 1: {file}");
                            continue;
                        }

                        using (var csvWriter = CsvDataWriter.Create(destFolder + '\\' + fileName, writerOptions))
                        {
                            try
                            {
                                csvWriter.Write(dr2);
                            }
                            catch
                            {
                                Console.WriteLine($"file 2: {file}");
                            }

                        }

                        dr.Close();
                    }

**Comment by MarkPflug** [comment]
Something like this should work:

```C#
var outputFile = "folder/merged.csv";

if (File.Exists(outputFile))
{
    File.Delete(outputFile);
}

var files = new string[] { };
bool first = true;

foreach (string file in files)
{
    var fileNameNoExt = Path.GetFileNameWithoutExtension(file);
    var dateInFileName = fileNameNoExt.Split('_')[4];
    using var dr = CsvDataReader.Create(file);

    // This is assuming that the input CSV files all have the same exact headers
    // int the same order.
    var dr2 = dr.WithColumns(
        new CustomDataColumn<string>("FilenameNoExt", _ => fileNameNoExt),
        new CustomDataColumn<string>("DateInFilename", _ => dateInFileName),
        new CustomDataColumn<int>("Row", _ => dr.RowNumber)
        );

    // only write headers for the first file.
    var writerOptions = new CsvDataWriterOptions
    {
        WriteHeaders = first,
    };

    first = false;

    // append to the output file.
    using var output = new StreamWriter("merged.csv", true);

    using (var csvWriter = CsvDataWriter.Create(output, writerOptions))
    {
        csvWriter.Write(dr2);
    }
}

```

**Comment by BabakRabie** [comment]
Worked perfectly! Thanks for the amazing support.
