### ISSUE TITLE
Invalid Examples for CSV Data Binding

### ISSUE THREAD

**Issue by AzeTheGreat** [MarkPflug/Sylvan#242]
I am attempting to parse a CSV into a list of objects, and then write that list back to a CSV.

However, the documentation doesn't seem to provide working examples and I'm struggling to figure out how to achieve this.

The [CSV Data Binder example](https://github.com/MarkPflug/Sylvan/blob/main/docs/Csv/Examples.md#csv-data-binder-example) shows a `GetRecords` method that is not present on `CsvDataReader` objects.  (It's also missing the `foreach` opening bracket, but that's an easy fix).

When writing, the `AsDataReader` extension does not appear to exist.

Complete (non-functional) example:
```cs
using Sylvan.Data;
using Sylvan.Data.Csv;

class Record
{
	public int Id { get; set; }
	public int Name { get; set; }
	public int Date { get; set; }

	static void Read()
	{
		using var csv = CsvDataReader.Create("demo.csv");
		foreach (var record in csv.GetRecords<Record>())
		{
			var id = record.Id;
			var name = record.Name;
			var date = record.Date;
		}
	}

	static async void Write()
	{
		var records = new[]
		{
			new {
				Id = 1,
				Name = "Alpha",
				Date = new DateTime(2021, 1, 1)
			}
		};

		var recordReader = records.AsDataReader();

		using var csvWriter = CsvDataWriter.Create("demo.csv");
		await csvWriter.WriteAsync(recordReader);
	}
}
```

Let me know if I'm just missing something simple here.

**Comment by MarkPflug** [comment]
You likely haven't added the Sylvan.Data package. The data binder is an extension method in that library, not a member on CsvDataReader. The data binder target DbDataReader, so it can be used with more than CsvDataReader. It can also be used with ExcelDataReader from the Sylvan.Data.Excel pacakge, for example.

The text above the example mentions this package:

> The Sylvan.Data library includes a generic data binder

You're not the first person to be confused by this, and I'd welcome suggestions on how to make it more clear.

**Comment by AzeTheGreat** [comment]
That does appear to be the issue, thank you.

I would say that revising that text to the below may improve clarity.
> The Sylvan.Data **package** includes a generic data binder

The overall flow for me was:
[Sylvan](https://github.com/MarkPflug/Sylvan/tree/main) - Looks like multiple separate, self contained packages.  I want to work with CSVs, so I choose  
[Sylvan.Data.Csv](https://github.com/MarkPflug/Sylvan/blob/main/docs/Csv/Sylvan.Data.Csv.md) - Summarizes the Csv handling package.  Installation only mentions the Sylvan.Data.Csv package.  I just want simple examples, so I go to  
[Usage Examples](https://github.com/MarkPflug/Sylvan/blob/main/docs/Csv/Examples.md) - Based on the overall structure to get here, everything seems to imply, "these code examples are for Sylvan.Data.Csv".

Hopefully that provides a bit of external insight as to the confusion.  I do see that the [Schema](https://github.com/MarkPflug/Sylvan/blob/main/docs/Csv/Sylvan.Data.Csv.md#features) section briefly calls out the Sylvan.Data package, but it didn't look relevant at all to my goals before reading the last 8 words.

I think there are a lot of potential improvements that could "solve" this.  Maybe break out the Sylvan.Data.Csv & Sylvan.Data code to a separate example page that is linked?
