### ISSUE TITLE
Type or namespace TypedCsvSchema() could not be found.

### ISSUE THREAD

**Issue by speyck** [MarkPflug/Sylvan#25]
This is probably a noob mistake, but I just can't use 'TypedCsvSchema()'. I think I'm just missing a using statement, but maybe it's something else?

**Code:**
```
var schema = new TypedCsvSchema()
    .Add(typeof(int))
    .Add(typeof(string))
    .Add(typeof(double), true)
    .Add(typeof(DateTime))
    .Add(typeof(DateTime), true);

var options = new CsvDataReaderOptions
{
	Schema = schema
};

dataTable = new DataTable();

dataTable.Load(CsvDataReader.Create("data.csv", options));
```

> Error CS0246: The type or namespace name 'TypedCsvSchema' could not be found (are you missing a using directive or an assembly reference?)

**Using statements:**
```
using Sylvan.Data.Csv; 
using Sylvan.Data; 
using System.Data.Common; 
```

**Comment by speyck** [comment]
Got the code from [Stackoverflow](https://stackoverflow.com/a/61256368/13574233) btw.

**Comment by MarkPflug** [comment]
The `TypedCsvSchema` class implementation was removed from the `Sylvan.Data.Csv` package a while ago. I kept adding more functionality to it but it became more general purpose than my original narrow usage, so I moved it into the `Sylvan.Data` package as the more general-purpose `Schema` class. The `Sylvan.Data` package is still pre-release though and it is still changing quite a bit, so I wouldn't recommend using it yet.

Instead, you can provide an implementation of TypedCsvSchema into your own code (just copy this code into a file in your project):
```C#
class TypedCsvColumn : DbColumn
{
    public TypedCsvColumn(Type type, bool allowNull)
    {
        // if you assign ColumnName here, it will override whatever is in the csv header
        this.DataType = type;
        this.AllowDBNull = allowNull;
    }
}
    
class TypedCsvSchema : ICsvSchemaProvider
{
    List<TypedCsvColumn> columns;

    public TypedCsvSchema()
    {
        this.columns = new List<TypedCsvColumn>();
    }

    public TypedCsvSchema Add(Type type, bool allowNull = false)
    {
        this.columns.Add(new TypedCsvColumn(type, allowNull));
        return this;
    }

    DbColumn? ICsvSchemaProvider.GetColumn(string? name, int ordinal)
    {
        return ordinal < columns.Count ? columns[ordinal] : null;
    }
}
```

You could then define the type schema for your CSV data by following this pattern:
```C#
// defines the types in column order
var schema = new TypedCsvSchema()
    .Add(typeof(int))
    .Add(typeof(string))
    .Add(typeof(double), true)
    .Add(typeof(DateTime))
    .Add(typeof(DateTime), true);

var options = new CsvDataReaderOptions
{
    Schema = schema
};

using var csv = CsvDataReader.Create("data.csv", options);
...
```

Why would you want to define a schema? Most often you would do this when you are going to hand the `CsvDataReader` (DbDataReader) off to an API that knows how to consume the schema data. `SqlBulkCopy` is a common example of such an API. You can also use `Dapper` library to bind the CSV data to an object if the CSV has a schema defined.

Given the schema defined above, you might have a record class like the following:
```C#
class MyDataRecord {
    public int Id {get;set;}
    public string Name {get;set;}
    public double? Value {get;set;}
    public DateTime CreateDate {get;set;}
    public DateTime? ModifiedDate {get;set;}
}
```
You could then create a generic extension method that uses Dapper to bind the `CsvDataReader` to the an object:
```C#
static IEnumerable<T> GetRecords<T>(this DbDataReader dr) {
    var binder = dr.GetRowParser<T>();
    while(dr.Read()){
        yield return binder(dr);
    }
}
```

Then to consume that class:
```C#
    foreach (MyDataRecord record in csv.GetRecords<MyDataRecord>())
    {
        Console.WriteLine($"{record.Name} {record.Value}");
    }
```

I put a complete sample here: https://github.com/MarkPflug/CsvBenchmarks/blob/main/source/CsvBenchmark/Samples.cs

Hope this gets things working for you. Happy to help if you have any other questions. If you could give this repository a star if you find it useful, I would greatly appreciate it!

... and thanks for the reminder that I need to work on documentation!

**Comment by MarkPflug** [comment]
Oh right, and that stackoverflow question was asking about loading `DataTable` specifically, so by defining a schema, the data types will flow in to the `DataTable` when you call `dataTable.Load(csv)`.

**Comment by speyck** [comment]
@MarkPflug thank you very much! I think I can make it work now.
