### ISSUE TITLE
Query: Nullable boolean CsvDataWriterOptions FalseString 

### ISSUE THREAD

**Issue by andrewbgittus** [MarkPflug/Sylvan#251]
We are using CsvDataWriter and CsvDataWriterOptions with the following options:

```
var opts = new CsvDataWriterOptions()
{
    TrueString = "Yes",
    FalseString = "No",
    Delimiter = ',',
    QuoteStrings = CsvStringQuoting.AlwaysQuote,
};
```

Within the data there is a boolean column which is nullable. Where the column has a null value an empty string is output not "No". Is it possible to treat null values as false?

**Comment by MarkPflug** [comment]
Yes. You'd need to do something to turn the null values into false, which can be done in one of a number of ways, but you haven't provided sufficient details for me to advise on the best approach.

**Comment by andrewbgittus** [comment]
Thanks for the response - let me know what details further you need, I've provided a little more insight below.

I've included the code we're using below. The dataSet is a result of execution of SQL and filling a DataTable which gets added to the DataSet.

```
var opts = new CsvDataWriterOptions()
 {
     TrueString = "Yes",
     FalseString = "No",
     Delimiter = ',',
     QuoteStrings = CsvStringQuoting.AlwaysQuote
 };

 using (var csvStream = new MemoryStream())
 using (var writer = new StreamWriter(csvStream, Encoding.UTF8))
 using (var csvWriter = CsvDataWriter.Create(writer, opts))
 {
     csvWriter.Write(dataSet.CreateDataReader());
     writer.Flush();

     return csvStream.ToArray();
 }
```

**Comment by MarkPflug** [comment]
If you're loading the DataTable from a database, you could also modify the query to replace the nulls with a `isnull` or `coalesce` so it is already correct when it is loaded.
