### ISSUE TITLE
Unable to provide custom FieldAccessors for use with a CsvSchema

### ISSUE THREAD

**Issue by JaseRandall** [MarkPflug/Sylvan#256]
@MarkPflug 

Following on from #254 

I'm using a CsvSchema and would like to provide custom FieldAccessors so I can cater to my specific requirements.

As you mentioned in #254, I can inherit DataReaderAdapter to override GetDateTime however, that function does not get called if using a CsvSchema; instead, it uses a function provided in CsvDataAccessor.Accessors:

```
        sealed class DateTimeAccessor : FieldAccessor<DateTime>
        {
	        internal static readonly DateTimeAccessor Instance = new();
        
	        public override DateTime GetValue(CsvDataReader reader, int ordinal)
	        {
		        return reader.GetDateTime(ordinal);
	        }
        }
```

I would like to provide my own MyDateTimeAccessor instead of using that one:

```
        sealed class MyDateTimeAccessor : FieldAccessor<DateTime>
        {
	        internal static readonly MyDateTimeAccessor Instance = new();
        
	        public override DateTime GetValue(CsvDataReader reader, int ordinal)
	        {
		        var value = reader.GetDateTime(ordinal);
		        if (value.Kind == DateTimeKind.Unspecified)
		        {
			        value = new DateTime(value.Ticks, DateTimeKind.Utc);
		        }
		        return value;
	        }
        } 
```

I have a proposed change here: https://github.com/JaseRandall/Sylvan/tree/Proposed-Change-to-allow-Providing-a-CustomAccessor-in-the-CsvDataAccessor-class so I can provide my own FieldAccessors.

The changes basically amount to:

Making `abstract class FieldAccessor<T> ` and `interface IFieldAccessor` public and adding the following method to change the default FieldAccessors to the custom accessors:

```
        internal static void ProvideCustomAccessor(Dictionary<Type, IFieldAccessor> customFieldAccessors)
	{
		foreach (var fieldAccessor in customFieldAccessors)
		{
			if (Accessors.ContainsKey(fieldAccessor.Key))
			{
				Accessors[fieldAccessor.Key] = fieldAccessor.Value;
				return;
			}
			Accessors.Add(fieldAccessor.Key, fieldAccessor.Value);
		}
	}
```

adding a property to CsvDataReaderOptions

`
	public Dictionary<Type, IFieldAccessor>? CustomFieldAccessors { get; set; }
`

Changing the CsvDataReader constructor:
```
        if (options.CustomFieldAccessors != null)
        {
	        CsvDataAccessor.ProvideCustomAccessor(options.CustomFieldAccessors);
        }
```

So, then I can do something like this:

```
public class CustomFieldAccessorTests
{
	[Fact]
	public void Test()
	{
		const string Data =
					"""
					a,b
					1,2022-01-13T12:33:45.1234567
					2,2022-01-13T12:33:45.1234567-08:00
					3,2022-01-13T12:33:45.1234567Z
					""";

		var schema = new CsvSchema(Schema.Parse("a:int,b:datetime"));
		var options = new CsvDataReaderOptions { Schema = schema, HasHeaders = true, CustomFieldAccessors = new Dictionary<Type, IFieldAccessor> { { typeof(DateTime), MyDateTimeAccessor.Instance } } };

		var csvReader = CsvDataReader.Create(new StringReader(Data), options);
		csvReader.Read();
		var x = csvReader[1];
		var y = csvReader.GetDateTime(1);
		Assert.Equal(DateTimeKind.Utc, ((DateTime)x).Kind);
		Assert.Equal(DateTimeKind.Unspecified, y.Kind);
	}
}

sealed class MyDateTimeAccessor : FieldAccessor<DateTime>
{
	internal static readonly MyDateTimeAccessor Instance = new();

	public override DateTime GetValue(CsvDataReader reader, int ordinal)
	{
		var value = reader.GetDateTime(ordinal);
		if (value.Kind == DateTimeKind.Unspecified)
		{
			value = new DateTime(value.Ticks, DateTimeKind.Utc);
		}
		return value;
	}
}
```

If you're agreeable to the change, I can submit a pull request? (Not sure if it needs more tests?)
Or we can discuss it further?

**Comment by MarkPflug** [comment]
Not sure if you see the notifications from the closed PR. I should have added my comments here:

I think you've pointed about a bug with the DataReaderAdapter.

Currently the indexers are implemented to delegate to the inner/wrapped datareader:

``` C#
	/// <inheritdoc/>
	public override object this[int ordinal] => dr[ordinal];

	/// <inheritdoc/>
	public override object this[string name] => dr[name];
```
These need to be fixed to be:
```C#
	/// <inheritdoc/>
	public override object this[int ordinal] => this.GetValue(ordinal);

	/// <inheritdoc/>
	public override object this[string name] => this.GetValue(this.GetOrdinal(name));
```

I will make this fix, which should allow this to work correctly. Until then, you can override these and fix it yourself, by adding this override to the adapter:
```
public override object this[int ordinal] => this.GetValue(ordinal);
```

I see the field access business as an internal implementation detail, and I really don't want to expose those as a public API if I can void it.

**Comment by JaseRandall** [comment]
Thanks @MarkPflug ! I'm still learning a lot so didn't pick up on that being a bug but makes sense now you've pointed it out.

I've worked out how I can implement my own version of field access for my DateTimeAdapter which will allow me to provide a custom class per data type or even column, if required. (I think I will end having files with UTC columns, or local time columns or needing strings cleaned which I would normally handle further along in the code, so being able to provide a custom class per use case is going to be very handy. Might speed some scenarios up and/or reduce memory usage.)

Thanks again and a very big thank you for sharing this library!! 😊
