### ISSUE TITLE
Possibility to have some string sanitization

### ISSUE THREAD

**Issue by hidegh** [MarkPflug/Sylvan#259]
Would it be possible to ensure all column values are first sanitized by some custom logic (function), thus: getting a sanitized string when calling GetString and also using that sanitized string when calling methods like GetDecimal, or GetBoolean (leading to less possible issues)?

```
private static Regex removeNonPrintableAndWhitespaceLeadingAndTrailing = new Regex(@"^[\p{C}\s]+|[\p{C}\s]+$", RegexOptions.Compiled | RegexOptions.Multiline);
```

**Comment by MarkPflug** [comment]
You can achieve this by wrapping the CsvDataReader in another DbDataReader that does the sanitization/validation. You can use the [DataReaderAdapter](https://github.com/MarkPflug/Sylvan/blob/main/source/Sylvan.Data/DataReaderAdapter.cs) from the `Sylvan.Data` package as a base class to provide the majority of the implementation, and just override `GetString(int ordinal)` to implement the sanitization logic.
