### ISSUE TITLE
Writing a list of dictionaries?

### ISSUE THREAD

**Issue by Hawxy** [MarkPflug/Sylvan#261]
Hi,
We have a csv validation process that basically returns the entire csv back to the user but with an additional column added for "errors" explaining why the row couldn't be parsed. By the time the data reaches this point it's in a `List<Dictionary<string, object>>` format with the headers being the keys and the values being the object. 

We currently use csvhelper for this as iterating over the keys/values to write the headers/rows is fairly straight forward but given we already using Sylvan for most of the parsing we'd like consolidate around these libraries. Is there an easy way to do this I'm missing or are we stuck with writing a custom DbDataReader to support the dictionary type?

**Comment by MarkPflug** [comment]
If your data is in a dictionary like that, then yeah you'd probably have to implement a DbDataReader over that. I'm assuming you're using a dictionary because the data schema is unknown at compile time?

**Comment by MarkPflug** [comment]
Feel free to reopen this if there is something that needs my attention.
