### ISSUE TITLE
(Req)

### ISSUE THREAD

**Issue by burnchar** [MarkPflug/Sylvan#265]
Feature idea: Get CSV schema from the properties of the specified generic type so that we can do generic CSV reads into objects of that type.

**Comment by MarkPflug** [comment]
This is already supported, I think:
```C#
using Sylvan.Data;
using Sylvan.Data.Csv;

SchemaRead();

static void SchemaRead()
{
    var data =
        """
        Id,Date,Name,Duration
        1,2020-01-01,Asdf,4:15:33
        2,2022-11-13,Qwer,
        """;

    var csv = CsvDataReader.Create(new StringReader(data));
    foreach (var record in csv.GetRecords<Record>())
    {
        Console.WriteLine($"{record.Name} {record.Duration}");
    }
}

class Record
{
    public int Id { get; set; }
    public DateTime Date { get; set; }
    public string Name { get; set; }
    public TimeSpan? Duration { get; set; }
}
```

Or, are you trying to describe something else? Perhaps a concrete example of what you're trying to accomplish would help explain.

**Comment by MarkPflug** [comment]
I guess maybe this is resolved then?

**Comment by burnchar** [comment]
My apologies for the incredibly late reply. Thank you, Mark, for your example. I really appreciate your library and the fact that you help the community.
