### ISSUE TITLE
Exception of type 'Sylvan.Data.Csv.CsvFormatException'

### ISSUE THREAD

**Issue by zraffaele** [MarkPflug/Sylvan#60]
Hi,
if i read a csv separated with comma and in a string he find a quote get the title exception

**Comment by MarkPflug** [comment]
You'll need to provide me a working example of code that doesn't work as you expect for me to be able to help you. That exception will be thrown when certain malformed fields are encountered, so I'm assuming the behavior your are seeing is by-design, but I can't be sure without seeing an example that reproduces the behavior.

**Comment by Aditya-0011** [comment]
Please check sample
TEST001|00000S8970986000320122023||22-11-2021||178721|100724106775191|114458810||ROSHN|"TULSI", D B ROAD, 852201|10|BIHAR||8709221003|||||||N||||||1||SMS Charges.|S|9971|1|No|15|15|15|0|0|0|||||||||2.7|18|||N|N|||Taxable||||||||||||
