### ISSUE TITLE
Unable to write IDataReader to CSV

### ISSUE THREAD

**Issue by nbeitner** [MarkPflug/Sylvan#69]
Out of interest, why does

public long Write(DbDataReader reader)

Require a DbDataReader?

Why don’t you use IDataReader?

Then you can support a much wider range of data sources.

I have an IDataReader that I wanted to save to csv, and I can’t because you require a much more complex contract, for which there seems to be no reason.

Any chance you can change the contract to support the IDataReader

**Comment by MarkPflug** [comment]
I'm going to close this and we can continue the existing conversation in #67. Link here: https://github.com/MarkPflug/Sylvan/issues/67#issuecomment-884367244

The short: DbDataReader was selected for the async APIs that it exposes and it is generally what most data providers implement these days. IDataReader can be converted to DbDataReader with the AsDbDataReader() extension exposed in the Sylvan.Data library.
