### ISSUE TITLE
Write List<T> to CSV with CsvDataWriter

### ISSUE THREAD

**Issue by Gerardo-Sista** [MarkPflug/Sylvan#71]
Hello,
thank you for this amazing lightning fast CSV library.
I use it to read million rows from CSV with no trouble.

The problem now is that I have to write CSV file from List<T>  (example: List(Person) peopleList).
What's the correct approach to write to a CSV file using your built in CsvDataWriter?

Thank you.

**Comment by MarkPflug** [comment]
You can use the `Sylvan.Data` nuget package to assist with this task. It includes an extension method `IEnumerable<T>.AsDataReader` that will provide a `DbDataReader` over a `List<T>`. This package is currently only prerelease, and some of the APIs will likely change a bit before I get around to an offical release. However, you can count on the `AsDataReader` extension method behavior. The `AsDataReader` extension method will expose all public properties on T as a column in the data set.

```
using Sylvan.Data;
using Sylvan.Data.Csv;

List<Person> data = GetPeople();
using var dataReader = data.AsDataReader();
using var csvWriter = CsvDataWriter.Create("people.csv");
csvWriter.Write(dataReader);
```

**Comment by Gerardo-Sista** [comment]
Thank you,
but it seems it doesn't work. 
In fact the only written text is the header with property names, but no data is written.

This is the output file, for my `List<User>` collection:
`IdUtente,Cognome,Nome,NomeUtente,PasswordHash,Note,DataRegistrazione,HasErrors`
but then no data is written (List has 2 records).
Please check the debug image saying "Enumeration yielded no results".

![image](https://user-images.githubusercontent.com/34858800/127113949-14edfc41-1919-4489-af48-9be812b4de8f.png)

**Comment by Gerardo-Sista** [comment]
Thank you, it seems it works fine.
