### ISSUE TITLE
How to Append records to an existing CSV file 

### ISSUE THREAD

**Issue by Gerardo-Sista** [MarkPflug/Sylvan#72]
Hello,
here I am here again with another question hoping to help also other people with same requirements.

CsvDataWriter has only Write(or WriteAsync), it seems it creates a new file or overwrites the existing same named file.

**SCENARIO:**
Database table hosting 1.000.000 records.
Read a batch of 10.000 record from db, then write to file, 
Read next batch of 10.000 records from Db then write to file....
....and so on.

Can you improve the library adding an `Append(string file, CsvDataWriterOptions options)`  or `AppendAsync` method to add new records to an existing file?

Thank you

**Comment by MarkPflug** [comment]
You can already do this by using `CsvDataWriter.Create(TextWriter)`, which allows you to control the construction and lifetime of the output stream. You can open a stream in append mode, wrap that in a StreamWriter, then hand that off to the CsvDataWriter. Here is an rough example:

```
for(int i = 0; ; i++) {
  DbDataReader dr = GetDataReaderBatch(i);
  if(dr == null) 
    break;
  
  // open the file in append mode
  using var s = File.Open("output.csv", FileMode.Append, FileAccess.ReadWrite, FileShare.None);
  using var tw = new StreamWriter(s);

  // only write the headers on the first batch.
  var opts = new CsvDataWriterOptions { WriteHeaders = (i == 0) };
  using var csvWriter = CsvDataWriter.Create(tw, opts);   
  csvWriter.Write(dr);
}
```

However, there really shouldn't be any need to do this batching. You should be able to just query the entire 1mil rows and write it in one go. The memory usage should be roughly the same either way, as my library streams the data to the output and doesn't need to load everything in memory at once.

**Comment by Gerardo-Sista** [comment]
Hello, thank you.
Batching is needed not because of your library, but because of retrieving data with EFcore.  Loading >10 millions row in a List<T> leads easily to memory overflow and also SRS requires maximum memory footprint to be less than 300 Mb.

Thank you for the code snippet. I'll test it as soon as possible!
