### ISSUE TITLE
strongly typed parsing is not working

### ISSUE THREAD

**Issue by kaustubh007** [MarkPflug/Sylvan#78]
i am trying to use the below code but it is not working 

var dataTable = new DataTable();

var schema = new CsvSchema(Sylvan.Data.Schema.Parse("Id:int,Name,Quantity:int,SalePrice:decimal"));
using var csv = CsvDataReader.Create("SalesData.csv", new CsvDataReaderOptions { Schema = schema});
dataTable.Load(csv);

I reviewed the source code and found the Sylvan.Data.Schema.Parse method, but it is not accessible.

**Comment by MarkPflug** [comment]
The Sylvan.Data.Schema type is defined in the Sylvan.Data package, not the Sylvan.Data.Csv package. Have you added both of them to your project? The Sylvan.Data package is currently only pre-release on nuget, so you might need to check the "pre-release" checkbox to find it. This code should work as-is if that package is added.

**Comment by MarkPflug** [comment]
I'm going to assume that you got this working. If not, open another issue and include an error message or a description of how "it is not working".
