### ISSUE TITLE
Last character of quoted cell is lost if CSV ends with this cell

### ISSUE THREAD

**Issue by timotheuspreisinger** [MarkPflug/Sylvan#99]
The last character of a cell with a quoted string seems to be lost if the CSV content ends with the closing quote character of this cell.

Assuming this CSV content
```
id;value
1;"cell"
```
is stored in a string: `"id;value\r\n1;\"cell\""`. Using a `Sylvan.Data.Csv.CsvDataReader` will read only the value `cel` for the last cell.

If I append a newline to the string (no matter if it is \r, \n, or \r\n), the last cell is read correctly.

I have prepared some code on: [dotnetfiddle](https://dotnetfiddle.net/nJ2wHG) and attached the file.

**Comment by MarkPflug** [comment]
It is fixed now, and I just pushed v1.1.11 with the fix. Might take a few minutes for nuget to index it. Thanks for the bug report!

**Comment by timotheuspreisinger** [comment]
Thank you! That was fast!
